name = "role_lottery"
target = "javascript"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 5.0.0 and < 6.0.0"
modem = ">= 2.0.1 and < 3.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
plinth = ">= 0.5.9 and < 1.0.0"
prng = ">= 4.0.1 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.2.2 and < 2.0.0"
birdie = ">= 1.3.2 and < 2.0.0"
trellis = ">= 2.0.0 and < 3.0.0"
